# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20170711_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemasok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('hp', models.CharField(max_length=16)),
                ('alamat', models.CharField(max_length=50)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
