# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_delete_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pemasok',
            options={'verbose_name_plural': 'list pemasok'},
        ),
    ]
