# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
