# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_detail_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='selling',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.Selling'),
            preserve_default=False,
        ),
    ]
