# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_detail_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='status',
            field=models.CharField(choices=[('PD', 'Paid'), ('UP', 'Unpaid')], default='UP', max_length=2),
        ),
    ]
