# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_pemasok'),
        ('products', '0008_produk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0006_selling_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetilPenjualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengadaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField(default=0)),
                ('harga', models.IntegerField(default=0)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('pemasok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Pemasok')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Produk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'SD', b'Sudah dibayar'), (b'BL', b'Belum dibayar')], default=b'BL', max_length=2)),
                ('pembeli', models.CharField(blank=True, max_length=50, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='selling',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Procurement',
        ),
        migrations.DeleteModel(
            name='Selling',
        ),
        migrations.AddField(
            model_name='detilpenjualan',
            name='penjualan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Penjualan'),
        ),
        migrations.AddField(
            model_name='detilpenjualan',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.Produk'),
        ),
    ]
