# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20170726_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detilpenjualan',
            options={'verbose_name_plural': 'list detil penjualan'},
        ),
        migrations.AlterModelOptions(
            name='pengadaan',
            options={'verbose_name_plural': 'list pengadaan'},
        ),
        migrations.AlterModelOptions(
            name='penjualan',
            options={'verbose_name_plural': 'list penjualan'},
        ),
        migrations.AlterField(
            model_name='penjualan',
            name='status',
            field=models.CharField(choices=[('SD', 'Sudah dibayar'), ('BL', 'Belum dibayar')], default='BL', max_length=2),
        ),
    ]
