# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20170728_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPengadaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
