# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_produk_modal'),
        ('transactions', '0010_detailpengadaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetilPengadaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField(default=0)),
                ('harga', models.IntegerField(default=0)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Produk')),
            ],
        ),
        migrations.DeleteModel(
            name='DetailPengadaan',
        ),
        migrations.RemoveField(
            model_name='pengadaan',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='pengadaan',
            name='kuantitas',
        ),
        migrations.RemoveField(
            model_name='pengadaan',
            name='produk',
        ),
    ]
