# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20170728_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detilpengadaan',
            options={'verbose_name_plural': 'list detail pengadaan'},
        ),
    ]
