# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170711_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
