# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170718_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.IntegerField(default=0)),
                ('detil', models.CharField(max_length=100)),
                ('berat', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=10, null=True)),
                ('stok', models.IntegerField(default=0)),
                ('dibuat_pada', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
