# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produk',
            options={'verbose_name_plural': 'list produk'},
        ),
        migrations.RemoveField(
            model_name='produk',
            name='detil',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='sku',
        ),
    ]
