# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20170728_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='modal',
            field=models.IntegerField(default=0),
        ),
    ]
